# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- development
pr:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'
steps:
- task: UseDotNet@2
  displayName: "install .net 3.1"
  inputs:
    packageType: 'runtime'
    version: '3.1.8'

- task: UseDotNet@2
  displayName: 'install .net from global json'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
- task: DotNetCoreCLI@2
  displayName: 'Install Nuke.GlobalTool'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install Nuke.GlobalTool --global'
- task: Bash@3
  continueOnError: true
  displayName: 'Clear NuGet Caches'
  inputs:
    targetType: 'inline'
    script: 'dotnet nuget locals all --clear'

- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'sources add -Name NukedBitOpen -Source https://pkgs.dev.azure.com/nukedbitorg/d4447947-ab69-4316-bc44-f5b5051314e9/_packaging/NukedBitOpen/nuget/v3/index.json -username nukedbit -password $(NUGET_API_KEY)'
- task: Bash@3
  displayName: 'Build'
  continueOnError: true
  inputs:
    filePath: './build.sh' 
    arguments: '-target PushNuGet'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults.xml'
    mergeTestResults: true
    searchFolder: '$(System.DefaultWorkingDirectory)/tests'
    testRunTitle: 'StackX Tests'